import {
    Apple,
    Archive,
    Angry,
    Aperture,
    AppWindow,
    AtSign,
    Backpack,
    Atom,
    Award,
    Balloon,
    Bath,
    Battery,
    Bed,
    BedDouble,
    Beef,
    Beer,
    BeerOff,
    Bird,
    Bike,
    Binoculars,
    BookA,
    Bookmark,
    BoomBox,
    Box,
    Brain,
    BrickWall,
    Briefcase,
    Bug,
    Brush,
    BrushCleaning,
    Building,
    Bus,
    Cake,
    Cable,
    Calendar,
    Camera,
    CandyCane,
    Carrot,
    Car,
    Cast,
    Cat,
    ChartBar,
    Church,
    Cigarette,
    Clapperboard,
    Clipboard,
    ClipboardCheck,
    Clock,
    Code,
    Compass,
    Croissant,
    Cross,
    Crown,
    CupSoda,
    Dice6,
    Disc3,
    Donut,
    DollarSign,
    Drill,
    Droplet,
    Dumbbell,
    Ear,
    Eye,
    Fish,
    Flame,
    Flashlight,
    Flag,
    Folder,
    Gift,
    Gamepad,
    Gem,
    Heart,
    Headphones,
    Highlighter,
    Hourglass,
    Hotel,
    Inbox,
    Key,
    Laptop,
    Landmark,
    Mountain,
    Motorbike,
    PartyPopper,
    Plane,
    Pizza,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Soup,
    Tag,
    MessageSquare,
} from "lucide-react";

export const GROUP_ICONS = [
    { id: 'default-icon', title: "Message", icon: MessageSquare},
    { id: 'icon-apple-id', title: 'Apple', icon: Apple },
    { id: 'icon-archive-id', title: 'Archive', icon: Archive },
    { id: 'icon-angry-id', title: 'Angry', icon: Angry },
    { id: 'icon-aperture-id', title: 'Aperture', icon: Aperture },
    { id: 'icon-appwindow-id', title: 'App Window', icon: AppWindow },
    { id: 'icon-atsign-id', title: 'At Sign', icon: AtSign },
    { id: 'icon-backpack-id', title: 'Backpack', icon: Backpack },
    { id: 'icon-atom-id', title: 'Science', icon: Atom },
    { id: 'icon-award-id', title: 'Award', icon: Award },
    { id: 'icon-balloon-id', title: 'Balloon', icon: Balloon },
    { id: 'icon-bath-id', title: 'Bath', icon: Bath },
    { id: 'icon-battery-id', title: 'Battery', icon: Battery },
    { id: 'icon-bed-id', title: 'Bed', icon: Bed },
    { id: 'icon-beddouble-id', title: 'Double Bed', icon: BedDouble },
    { id: 'icon-beef-id', title: 'Meat', icon: Beef },
    { id: 'icon-beer-id', title: 'Beer', icon: Beer },
    { id: 'icon-beeroff-id', title: 'No Alcohol', icon: BeerOff },
    { id: 'icon-bird-id', title: 'Bird', icon: Bird },
    { id: 'icon-bike-id', title: 'Bicycle', icon: Bike },
    { id: 'icon-binoculars-id', title: 'Binoculars', icon: Binoculars },
    { id: 'icon-booka-id', title: 'Book', icon: BookA },
    { id: 'icon-bookmark-id', title: 'Bookmark', icon: Bookmark },
    { id: 'icon-boombox-id', title: 'Music', icon: BoomBox },
    { id: 'icon-box-id', title: 'Box', icon: Box },
    { id: 'icon-brain-id', title: 'Brain', icon: Brain },
    { id: 'icon-brickwall-id', title: 'Wall', icon: BrickWall },
    { id: 'icon-briefcase-id', title: 'Work', icon: Briefcase },
    { id: 'icon-bug-id', title: 'Bug', icon: Bug },
    { id: 'icon-brush-id', title: 'Brush', icon: Brush },
    { id: 'icon-brushcleaning-id', title: 'Cleaning', icon: BrushCleaning },
    { id: 'icon-building-id', title: 'Building', icon: Building },
    { id: 'icon-bus-id', title: 'Bus', icon: Bus },
    { id: 'icon-cake-id', title: 'Cake', icon: Cake },
    { id: 'icon-cable-id', title: 'Tech', icon: Cable },
    { id: 'icon-calendar-id', title: 'Calendar', icon: Calendar },
    { id: 'icon-camera-id', title: 'Camera', icon: Camera },
    { id: 'icon-candycane-id', title: 'Holiday', icon: CandyCane },
    { id: 'icon-carrot-id', title: 'Vegetables', icon: Carrot },
    { id: 'icon-car-id', title: 'Car', icon: Car },
    { id: 'icon-cast-id', title: 'Streaming', icon: Cast },
    { id: 'icon-cat-id', title: 'Cat', icon: Cat },
    { id: 'icon-chartbar-id', title: 'Stats', icon: ChartBar },
    { id: 'icon-church-id', title: 'Religion', icon: Church },
    { id: 'icon-cigarette-id', title: 'Smoking', icon: Cigarette },
    { id: 'icon-clapperboard-id', title: 'Movie', icon: Clapperboard },
    { id: 'icon-clipboard-id', title: 'Clipboard', icon: Clipboard },
    { id: 'icon-clipboardcheck-id', title: 'Checklist', icon: ClipboardCheck },
    { id: 'icon-clock-id', title: 'Time', icon: Clock },
    { id: 'icon-code-id', title: 'Code', icon: Code },
    { id: 'icon-compass-id', title: 'Direction', icon: Compass },
    { id: 'icon-croissant-id', title: 'Bakery', icon: Croissant },
    { id: 'icon-cross-id', title: 'Health', icon: Cross },
    { id: 'icon-crown-id', title: 'Priority', icon: Crown },
    { id: 'icon-cupsoda-id', title: 'Soda', icon: CupSoda },
    { id: 'icon-dice6-id', title: 'Games', icon: Dice6 },
    { id: 'icon-disc3-id', title: 'Record', icon: Disc3 },
    { id: 'icon-donut-id', title: 'Sweets', icon: Donut },
    { id: 'icon-dollarsign-id', title: 'Finances', icon: DollarSign },
    { id: 'icon-drill-id', title: 'Tools', icon: Drill },
    { id: 'icon-droplet-id', title: 'Liquid', icon: Droplet },
    { id: 'icon-dumbbell-id', title: 'Fitness', icon: Dumbbell },
    { id: 'icon-ear-id', title: 'Hearing', icon: Ear },
    { id: 'icon-eye-id', title: 'Visual', icon: Eye },
    { id: 'icon-fish-id', title: 'Fish', icon: Fish },
    { id: 'icon-flame-id', title: 'Fire', icon: Flame },
    { id: 'icon-flashlight-id', title: 'Light', icon: Flashlight },
    { id: 'icon-flag-id', title: 'Flag', icon: Flag },
    { id: 'icon-folder-id', title: 'Files', icon: Folder },
    { id: 'icon-gift-id', title: 'Gift', icon: Gift },
    { id: 'icon-gamepad-id', title: 'Gaming', icon: Gamepad },
    { id: 'icon-gem-id', title: 'Value', icon: Gem },
    { id: 'icon-heart-id', title: 'Love', icon: Heart },
    { id: 'icon-headphones-id', title: 'Audio', icon: Headphones },
    { id: 'icon-highlighter-id', title: 'Highlight', icon: Highlighter },
    { id: 'icon-hourglass-id', title: 'Waiting', icon: Hourglass },
    { id: 'icon-hotel-id', title: 'Hotel', icon: Hotel },
    { id: 'icon-inbox-id', title: 'Inbox', icon: Inbox },
    { id: 'icon-key-id', title: 'Security', icon: Key },
    { id: 'icon-laptop-id', title: 'Computer', icon: Laptop },
    { id: 'icon-landmark-id', title: 'Landmark', icon: Landmark },
    { id: 'icon-mountain-id', title: 'Nature', icon: Mountain },
    { id: 'icon-motorbike-id', title: 'Motorbike', icon: Motorbike },
    { id: 'icon-partypopper-id', title: 'Celebration', icon: PartyPopper },
    { id: 'icon-plane-id', title: 'Travel', icon: Plane },
    { id: 'icon-pizza-id', title: 'Pizza', icon: Pizza },
    { id: 'icon-shoppingbag-id', title: 'Shopping Bag', icon: ShoppingBag },
    { id: 'icon-shoppingbasket-id', title: 'Shopping Basket', icon: ShoppingBasket },
    { id: 'icon-shoppingcart-id', title: 'Shopping Cart', icon: ShoppingCart },
    { id: 'icon-soup-id', title: 'Soup', icon: Soup },
    { id: 'icon-tag-id', title: 'Price Tag', icon: Tag },
];
export const getIcon = (id: string) => {
    const iconObject = GROUP_ICONS.find((item) => item.id === id);
    
    return iconObject ? iconObject.icon : MessageSquare;
};